backend:
 name: git-gateway
 branch: main

media_folder: static/images
public_folder: ../../static/images/

collections: 
 - name: "my-articles"
   preview: false
   label: "My Articles"
   folder: "content/my-articles"
   create: true
   slug: "{{slug}}"
   fields:
    - { label: "Title", name: "title", widget: "string" }   
    - { label: "Publication Date", name: "date", widget: "datetime", format: "yyyy-MM-dd" }
    - { label: "Post Url", name: "url", widget: "string" }
    - { label: "Post Category", name: "category", widget: "string" }
    - { label: "Tags", name: "tags", widget: "list" }
    - { label: "Featured Image", name: featured-image, widget: image }
    - { label: "Body", name: "body", widget: "markdown" }
 - name: "pages"
   preview: false
   label: "Pages"
   folder: "content/pages"
   create: true
   slug: "{{slug}}"
   fields:
   - { label: "Page Title", name: "title", widget: "string" }
   - { label: "Slug", name: "slug", widget: "string" }
   - { label: "Featured Image", name: featured-image, widget: image } 
   - { label: "Body", name: "body", widget: "markdown" }